### ISSUE TITLE
Problem with confirmation of registration

### ISSUE THREAD

**Issue by Asche98** [GralDispersionModel/GRAL#36]
Hello! I need to register on gral.tugraz.at to download GRAL, but I've got a problem with confirmation of registration. Letter with activation link can't be delivered for any emails (there is not in junkfolder). Maybe, it is some technical problem in your site (for example, something wrong with cron). I beg you to help me to solve this problem. I really need to download gral model for education purposes.

**Comment by MarkusKuntner** [comment]
thanks for the feedback, unfortunately there was a problem with the homepage which should be fixed now

**Comment by ireneormazabal** [comment]
Hello, I registered and I didn´t receive the verification link. Could you please tell me what might be the problem?
